package com.mobdeve.s15.g16.restroomlocator.utils;

public class ActivityNames {
    public static String
        ADD_RESTROOM_ACTIVITY = "ADD_RESTROOM_ACTIVITY",
        CHANGE_PASSWORD_ACTIVITY = "CHANGE_PASSWORD_ACTIVITY",
        LOGIN_ACTIVITY = "LOGIN_ACTIVITY",
        SIGN_UP_ACTIVITY = "SIGN_UP_ACTIVITY",
        USER_PROFILE_ACTIVITY = "USER_PROFILE_ACTIVITY",
        VIEW_RESTROOMS_NEARBY_ACTIVITY = "VIEW_RESTROOMS_NEARBY_ACTIVITY",
        VIEW_REVIEW_DETAILS_ACTIVITY = "VIEW_REVIEW_DETAILS_ACTIVITY",
        VIEW_REVIEWS_ACTIVITY = "VIEW_REVIEWS_ACTIVITY";
}
